### ISSUE TITLE
TO DO AFTER MERGE OF `FIX FORMATTING`

### ISSUE THREAD

**Issue by powerswing** [ztsv-av/spellbook#19]
- [x] place `lr_decay_steps` in global vars (`magicClassification.py`) - it is now an explicit var
 - [x] place `lr_decay_steps` in global vars (`magicDetection.py`) - it is now an explicit var
 - [x] `save_csvs_dir` is bad naming for a var - need to be changed

**Comment by ztsv-av** [comment]
done.
